main: com.ar.askgaming.NoCheatPlease
name: NoCheatPlease
version: 1.0
api-version: 1.21
author: AskGaming
description: NoCheatPlease
depend: [packetevents]
commands:
  ncp:
    description: NoCheatPlease
    usage: /ncp
    permission: nocheatplease.use
    aliases: [ncp]
